name: '❌ Build error'
description: 'Report errors when building from source code'
title: '[Build Error]: '
labels:
- 'build error'
body:
- type: markdown
  attributes:
    value: 'Please make sure to [search for existing issues](https://github.com/lencx/ChatGPT/issues) before filing a new one!'
- type: markdown
  attributes:
    value: 'Make sure to build from the latest version of the source code.'
- type: checkboxes
  attributes:
    label: Checklist
    options:
    - label: |
        This issue is related to a problem when **building** from the source code. For regular errors unrelated to **building** please file a regular `Bug report`.
      required: true
    - label: |
        I have given this issue a descriptive title starting with `[Build Error]:` such as `[Build Error]: Error when compiling, cannot find module`
      required: true
- type: markdown
  attributes:
    value: |
      ## Build error report
      Fill in the following information to help us reproduce the bug:
- type: textarea
  id: error
  attributes:
    label: Error message
    description: |
      Paste error messages here. If you have a lot of messages and it's getting too lengthy, save them in a text file then drag and drop the file into this textbox.
  validations:
    required: true
- type: input
  id: OS
  attributes:
    label: OS
    description: 'Specify the OS version you are using.'
    placeholder: 'e.g. Ubuntu 22.04, Windows 11 Pro'
  validations:
    required: true
- type: textarea
  id: environment
  attributes:
    label: Environment
    description: 'If you think your environment may be related to the problem, please describe it here.'
